#при удалении блока version build падает с ошибкой
version: "3.7"
services:
  db_movies:
    build:
      context: ./deploy/database
      dockerfile: Dockerfile
    container_name: db_movies
    restart: always
    env_file:
      - ./deploy/envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - movie_network
  es:
    build:
      context: .
      dockerfile: deploy/elasticsearch/Dockerfile
    container_name: es
    restart: always
    volumes:
      - es_data:/var/lib/es/data/
    ports:
      - 9200:9200
    networks:
      - movie_network
volumes:
  postgres_data:
  es_data:
networks:
  movie_network:
