FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.1-arm64
ENV discovery.type=single-node
EXPOSE 9200:9200

#docker run -p :9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.15.1-arm64
