#при удалении блока version build падает с ошибкой
version: "3.7"
services:
  db_movies:
    build:
      context: ./deploy/database
      dockerfile: Dockerfile
    container_name: db_movies
    restart: always
    env_file:
      - ./deploy/envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - movie_network
  es:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: es
    restart: always
    volumes:
      - es_data:/var/lib/es/data/
    ports:
      - 9200:9200
    networks:
      - movie_network
#  app:
#    build:
#      context: ./movies_admin
#      dockerfile: Dockerfile
#    container_name: app
#    restart: always
#    env_file:
#      - deploy/envs/django.env
#    networks:
#      - movie_network
#    depends_on:
#      - db_movies
#
#  web:
#    image: nginx:1.19.2
#    volumes:
#        - ./deploy/nginx/src/nginx.conf:/etc/nginx/nginx.conf:ro
#        - ./deploy/nginx/src/conf.d:/etc/nginx/conf.d:ro
#        - ./movies_admin/static:/home/app/web/static
#        - ./movies_admin/media:/home/app/web/media
#    ports:
#        - 80:80
#    container_name: web_serv
#    restart: always
#    env_file:
#      - ./deploy/envs/nginx.env
#    networks:
#      - movie_network
#    depends_on:
#      - app
volumes:
  postgres_data:
  es_data:
networks:
  movie_network:
