FROM docker.elastic.co/elasticsearch/elasticsearch:7.15.1-arm64
ENV discovery.type=single-node
EXPOSE 9200:9200
#RUN bash <(curl -s https://code.s3.yandex.net/middle-python/learning-materials/es_schema.txt)
